---
output:
  html_document: default
  pdf_document: default
---

# Health Scotland Project

## Project Description Outline

### Names of group members

Michael Boyne, Veronika Moroz, Matthew Willkins

### Roles & responsibilities of each member

**Michael** worked on skeleton for dashboard and he worked on alcohol specific data 
analysis and plotting for tab 3 (regional overview). 

**Veronika** worked on general data of inpatient cases in Scotland by sex and gender 
for tab 1 (overview), she also did tab 2 (spatial data) which is spatial data analysis by health boards.

**Matthew** worked on general data of inpatient cases in Scotland by specialty for tab 1 
(overview), he also started the work on the presentation and map, whilst also creating
Trello page.

Everyone worked on different elements in the dashboard and overall collaborative approach.

### Brief description of dashboard topic

Our dashboard contains the visualisation of the annual number of inpatient stays in hospitals for the last 10 years in Scotland which can be further differentiated by gender, sex and specialty.

Our health topic is focused on conditions that are caused by the abuse of alcohol. 
It shows that different health boards have various rate of stays caused by different
conditions related to alcohol. It helps the NHS and public health Scotland identify
which areas taken the highest proportion of patients that have conditions that are 
alcohol related (either mental or physical). Alcohol related conditions treated by
Scottish hospitals and displayed geographically by NHS health boards. 

### Stages of the project

Through discussion on zoom, we planned the work and project. 
Using an interactive drawing tool, we visualised the dashboard. 

Thursday/ Friday - planning and preparing for the weekend individual task, choosing 
a dataset by shortly wrangling in R
Sat/Sun - Data cleaning, wrangling and plotting
Mon - wrangling of new data, skeleton for dashboard, 'client Q&A'
Tue - start dashboard and individual plots (tabs)
Wed - merge using git and create map together, start presentation
Thur - prepare presentation, rehearse it, finalise dashboard, fill the written document
Friday - the day of group presentation


### Which tools were used in the project

Zoom (daily stand-ups and occasional mob programming)
Trello (planning & task allocation)
Git/GitHub (collaboration & version control)
ExcaliDraw to visualise the dashboard
Slack for communication

### How did you gather and synthesise requirements for the project?

We gathered open data on NHS and Scottish government websites.
We used the Q&A session with ‘the client’ to get an understanding of the project 
through asking the questions such as:

Q: How would you like to see the data visualised?
Q: Would the client be interested in regional data?
Q: What are the most important goals for the client and the metrics they want to see?

We prioritised the data that was capable of telling the story over the required
time frame of general health population and specific health problem.


### Motivations for using the data you have chosen

We used the dataset on clinical admissions (by age, sex and department) to answer 
the amount of admissions and length of stays (count and ratio) and because it was 
fairly tidy data to work with and it was covering the last 10 year period (no 
missing data). Alcohol related hospital data was also chosen as it has the possibility
to show variations between different NHS health boards.

### Data quality and potential bias, including a brief summary of data cleaning and transformations

There was a short description of the data but to understand the quality, we had to
investigate the data ourselves. After investigation, we determined the data was
a good quality. The data quality was also checked by Information Services Division (ISD). Based on the data sources, we can conclude that the data is not 
biased.

To clean the datasets we used janitor (clean_names) and tidyverse package to fulfill 
cleaning needs (e.g. str_to_lower, str_detect, mutate, factor, etc. )


### How is the data on statistics.gov.scot stored and structured

The data on statistics.gov.scot is in the form of linked data.

This means that data is linked to other datasets and very powerful in terms of 
quick findings. 

Benefits of storing the data like this are easy updating between various sources,
data is stored in defined schema, IDs are unique as stored as url's.


### Ethical and legal considerations of the data

It is ethically acceptable because it is legally open data and does not contain any 
personal data of individuals. As the data came from NHS health boards, it has been 
assumed that every data provider confirmed their consent. 

The datasets are covered by the Open Government License, which means they are free
to be copied, published, distributed and transmitted. It is free to adapt the Information and exploit it commercially or non-commercially. 



